package it.spe.disim.univaq.porting;

import it.spe.disim.univaq.porting.util.PortingUtil;

import java.io.File;
import java.io.IOException;
import java.io.ObjectInputStream.GetField;
import java.net.URI;
import java.net.URISyntaxException;

import org.apache.commons.io.FileUtils;
import org.eclipse.epsilon.common.parse.AST;
import org.eclipse.epsilon.common.util.AstUtil;
import org.eclipse.epsilon.epl.EplModule;
import org.eclipse.epsilon.evl.EvlModule;
import org.eclipse.epsilon.evl.parse.EvlParser;
import org.eclipse.epsilon.ewl.EwlModule;

public class MainTest {

	public static void main(String[] args) throws URISyntaxException, Exception {
		MainTest test = new MainTest();

		/** Epl -> Evl & Epl -> Ewl **/
		EplModule eplM = new EplModule();
		eplM.parse(test.getFileURI("/epl/basic.epl"));
		AST eplAST = eplM.getAst();
		AST ewlASTGen = Epl2Ewl.epl2ewl(eplAST);
		PortingUtil.ast2file(ewlASTGen, "autogenerated", "ewl");
		eplM.parse(test.getFileURI("/epl/basic.epl"));
		AST evlASTGen = Epl2Evl.epl2evl(eplAST);
		PortingUtil.ast2file(evlASTGen, "autogenerated", "evl");

		/** Evl -> Epl & Evl -> Ewl **/
		EvlModule evlM = new EvlModule();
		evlM.parse(test.getFileURI("/evl/basic.evl"));
		AST evlAST = evlM.getAst();
		AST eplASTGen = Evl2Epl.evl2epl(evlAST);
		ewlASTGen = Evl2Ewl.evl2ewl(evlAST);
		PortingUtil.ast2file(eplASTGen, "autogenerated", "epl");
		evlM.parse(test.getFileURI("/evl/basic.evl"));
		evlAST = evlM.getAst();
		PortingUtil.ast2file(ewlASTGen, "autogenerated", "ewl");

		/** Ewl -> Epl & Ewl -> Evl **/
		// PortingUtil.ast2file(eplASTGen, "autogenerated", "epl");
		// PortingUtil.ast2file(ewlASTGen, "autogenerated", "ewl");

	}

	public URI getFileURI(String fileName) throws URISyntaxException {

		URI binUri = getClass().getResource(fileName).toURI();
		URI uri = null;

		if (binUri.toString().indexOf("bin") > -1) {
			uri = new URI(binUri.toString().replaceAll("bin", "src"));
		} else {
			uri = binUri;
		}
		return uri;
	}
}
